LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := libncurses

TERMINFO_SOURCE := $(LOCAL_PATH)/terminfo/
TERMINFO_TARGET := $(TARGET_OUT)/usr/share/terminfo/
$(TERMINFO_TARGET):
	@echo "Install: $(TERMINFO_SOURCE) -> $(TERMINFO_TARGET)"
	@mkdir -p $@
	@cp -r $(TERMINFO_SOURCE)/* $@

ALL_DEFAULT_INSTALLED_MODULES += $(TERMINFO_TARGET)
ALL_MODULES.$(LOCAL_MODULE).INSTALLED := \
    $(ALL_MODULES.$(LOCAL_MODULE).INSTALLED) $(TERMINFO_TARGET)
